engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
 scss-lint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      	#mass_threshold: 30
      - javascript
ratings:
  paths:
  - "demo/**"
  - "src/**"